# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16",
  "iPhone 16 Pro Max"
])

languages([
  "en-US"
  # Add more languages as needed
  # "de-DE",
  # "it-IT",
  # ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("temp_0_Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Choose which project/workspace to use
project("./temp_0.xcodeproj")

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
